export const PRICING: Record<string, { input: number; output: number; tier: string }> = {
  "gpt-4o": { input: 2.5, output: 10, tier: "frontier" },
  "gpt-4.1": { input: 2, output: 8, tier: "frontier" },
  "gpt-4.1-mini": { input: 0.4, output: 1.6, tier: "economy" },
  "gpt-4o-mini": { input: 0.15, output: 0.6, tier: "economy" },
  "claude-opus-4": { input: 15, output: 75, tier: "frontier" },
  "claude-sonnet-4": { input: 3, output: 15, tier: "standard" },
  "claude-haiku-4": { input: 0.8, output: 4, tier: "economy" },
  "gemini-2.5-flash": { input: 0.15, output: 0.6, tier: "economy" },
  "llama-3.1-8b-instant": { input: 0.05, output: 0.08, tier: "economy" },
  "llama-3.3-70b-versatile": { input: 0.59, output: 0.79, tier: "standard" },
  "deepseek-chat": { input: 0.27, output: 1.1, tier: "economy" },
  "promptimizer-nano": { input: 0.05, output: 0.1, tier: "economy" },
  "promptimizer-flash": { input: 0.3, output: 0.9, tier: "standard" },
  "promptimizer-frontier": { input: 5, output: 15, tier: "frontier" },
  // Baseten Inference Model APIs (approx public list rates, $/1M tokens)
  "thinkingmachines/inkling-small": { input: 0.1, output: 0.4, tier: "economy" },
  "thinkingmachines/inkling": { input: 0.4, output: 1.6, tier: "standard" },
  "openai/gpt-oss-120b": { input: 0.15, output: 0.6, tier: "standard" },
  "zai-org/GLM-4.7": { input: 0.4, output: 1.5, tier: "standard" },
  "zai-org/GLM-5.2": { input: 0.6, output: 2.2, tier: "standard" },
  "zai-org/GLM-5.2-Fast": { input: 0.35, output: 1.4, tier: "standard" },
  "zai-org/GLM-5.3": { input: 0.8, output: 3.2, tier: "frontier" },
  "zai-org/GLM-5.3-Flash": { input: 0.45, output: 1.8, tier: "standard" },
  "zai-org/GLM-5.3-Fast": { input: 0.5, output: 2.0, tier: "standard" },
  "moonshotai/Kimi-K2.6": { input: 0.55, output: 2.2, tier: "standard" },
  "moonshotai/Kimi-K2.7-Code": { input: 0.55, output: 2.2, tier: "standard" },
  "moonshotai/Kimi-K3": { input: 0.9, output: 3.5, tier: "frontier" },
  "deepseek-ai/DeepSeek-V4-Flash-0731": { input: 0.2, output: 0.8, tier: "standard" },
  "deepseek-ai/DeepSeek-V4-Pro": { input: 0.7, output: 2.8, tier: "standard" },
  "deepseek-ai/DeepSeek-V4-Pro-0813": { input: 0.7, output: 2.8, tier: "standard" },
  "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B": { input: 1.2, output: 4.8, tier: "frontier" },
};

export const BENCHMARK = [
  { id: "e01", difficulty: 1, category: "factual_recall", prompt: "What is the capital of France?", must_include: ["Paris"], gold: "Paris is the capital of France." },
  { id: "e02", difficulty: 1, category: "factual_recall", prompt: "Convert 100 degrees Fahrenheit to Celsius. Give the number only.", must_include: ["37"], gold: "37.8" },
  { id: "e03", difficulty: 1, category: "factual_recall", prompt: "What does HTTP stand for?", must_include: ["HyperText Transfer Protocol", "Hypertext Transfer Protocol"], gold: "HyperText Transfer Protocol" },
  { id: "e04", difficulty: 1, category: "math", prompt: "What is 17 * 24?", must_include: ["408"], gold: "408" },
  { id: "e05", difficulty: 2, category: "summarization", prompt: "In two sentences, explain what a REST API is.", must_include: ["HTTP", "resource"], gold: "A REST API is an HTTP interface that exposes resources through uniform methods like GET and POST." },
  { id: "m01", difficulty: 3, category: "code_generation", prompt: "Write a Python function merge_sorted(a, b) that merges two sorted lists into one sorted list in O(n) time. Include a brief docstring.", must_include: ["def merge_sorted", "while"], gold: "def merge_sorted(a, b): while ..." },
  { id: "m02", difficulty: 3, category: "code_debug", prompt: "This function is supposed to return the first missing positive integer but fails on [3,4,-1,1]. Explain the bug and give a correct O(n) in-place solution.\n\ndef first_missing(nums):\n    return min([i for i in range(1, len(nums)+2) if i not in nums])", must_include: ["O(n)", "index"], gold: "The given code is O(n^2)." },
  { id: "m03", difficulty: 3, category: "analysis", prompt: "Compare TCP and UDP. Give three concrete situations where UDP is the better choice.", must_include: ["latency", "UDP"], gold: "UDP is better for live video, DNS, and games." },
  { id: "m04", difficulty: 3, category: "math", prompt: "A fair coin is flipped until the first heads. What is the expected number of flips? Show the equation.", must_include: ["2"], gold: "E = 2" },
  { id: "m05", difficulty: 3, category: "translation", prompt: "Translate to concise professional English: 'El despliegue falló porque el secreto de la base de datos no estaba montado en el pod.'", must_include: ["database", "secret"], gold: "The deployment failed because the database secret was not mounted into the pod." },
  { id: "h01", difficulty: 5, category: "system_design", prompt: "Design a rate limiter that supports 1 million QPS across 50 edge regions, per-API-key quotas, and burst tokens. Discuss consistency, failure modes, and a concrete Redis/data-plane sketch.", must_include: ["token bucket", "Redis", "eventual"], gold: "Distributed token bucket on Redis with eventual refill." },
  { id: "h02", difficulty: 5, category: "reasoning", prompt: "Prove that there are infinitely many prime numbers. Then explain why the same idea does not immediately prove there are infinitely many twin primes.", must_include: ["Euclid", "contradiction", "twin"], gold: "Euclid construction does not produce twins." },
  { id: "h03", difficulty: 4, category: "code_debug", prompt: "A Go server increments a map counter from many goroutines and occasionally loses counts or panics. Diagnose the race and write a correct design (mutex or sharding) with a short rationale.", must_include: ["mutex", "race", "map"], gold: "Go maps are not goroutine-safe." },
  { id: "h04", difficulty: 5, category: "system_design", prompt: "You must cut LLM cost 80% on a support desk without dropping answer quality on refunds, legal, and medical-adjacent tickets. Propose a routing + evaluation policy, including how you detect silent quality regressions.", must_include: ["route", "eval", "gold"], gold: "Route by risk. Eval against gold. Escalate on regression." },
  { id: "h05", difficulty: 4, category: "analysis", prompt: "A/B test: variant B increased conversion 2.1% (p=0.048) after peeking every day for two weeks. Should we ship B? Walk through the statistical issue and a correct procedure.", must_include: ["peeking", "multiple", "sequential"], gold: "Peeking invalidates p=0.048." },
];
